/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f103xx_adc_driver.h"
#include "stm32f103xx_gpio_driver.h"

int main(void)
{
	GPIO_PeriClockControl(GPIOA , ENABLE);
	ADC_PeriClockControl(ADC1 , ENABLE);

	GPIO_Handle_t ADC_Pin;
	ADC_Pin.pGPIOx = GPIOA;
	ADC_Pin.PinConfig.PinNumber = GPIO_PIN_5;
	ADC_Pin.PinConfig.Mode = GPIO_MODE_INPUT;
	ADC_Pin.PinConfig.CNF=GPIO_CNF_IN_ANALOG;
	ADC_Pin.PinConfig.InterruptPin = DISABLE;
	GPIO_Init(&ADC_Pin);

	GPIO_Handle_t LED;
	LED.pGPIOx = GPIOA;
	LED.PinConfig.PinNumber = GPIO_PIN_7;
	LED.PinConfig.Mode = GPIO_MODE_OUT_10MHz;
	LED.PinConfig.CNF=GPIO_CNF_OUT_PP;
	LED.PinConfig.OutputType = GPIO_OUTPUT_PUSHPULL ;
	GPIO_Init(&LED);

	ADC_Handle_t Tsensor ;
	Tsensor.pADCx = ADC1;
	Tsensor.ADC_Config.ADC_Channel = ADC_CHANNEL_5;
	Tsensor.ADC_Config.ADC_ContinuousConv = ADC_Single_Conversion;
	Tsensor.ADC_Config.scanMode = ADC_SCAN_DISABLE;
	Tsensor.ADC_Config.dataAlignment=ADC_Right_D_ALignment;
	Tsensor.ADC_Config.ADC_Prescaler = ADC_PRESCALER_4;
	Tsensor.ADC_Config.ADC_SampleTime = ADC_SAMPLE_239_CYCLES;
	ADC_Init(&Tsensor);

    ADC_Enable(ADC1);
	ADC_Enable(ADC1);

	float analog_val;
	float temp;

	while(1)
	{

		ADC_Calibrate(ADC1);

        ADC_StartConversion(ADC1);

        uint16_t raw = ADC_ReadValue(ADC1);

		analog_val = (raw * 3.3) / 4096.0 ;
		temp = ( analog_val )/0.01 ;

		if(temp> 40)
		{
            GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_7, ENABLE) ;
		}else
		{
			GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_7, DISABLE) ;
		}

	}

}
